const express = require('express');
const orderRouter = express.Router();
const {placeOrder,verifyOrder, userOrders,listOrder,updateState} = require('../controllers/orderController');
const authMiddleware = require('../middleware/auth');
orderRouter.post('/place', authMiddleware, placeOrder);
orderRouter.post('/verify' , verifyOrder);
orderRouter.get('/list', listOrder);
orderRouter.post('/userorders', authMiddleware, userOrders);
orderRouter.get('/status', updateState);
module.exports = orderRouter;